language: android
jdk: oraclejdk7

android:
  components:
    - build-tools-22.0.1
    - android-22
    - extra
    - sys-img-armeabi-v7a-android-22

install:
   - TERM=dumb
   
   # Emulator Management: Create, Start and Wait
before_script:
    - echo no | android create avd --force -n test -t android-22 --abi armeabi-v7a
    - emulator -avd test -no-skin -no-audio -no-window &
    - android-wait-for-emulator
    - adb shell input keyevent 82 &
       
script:
    - ./test_script.sh
    
licences:
    - /android-sdk-license-[0-9a-f]{8}/
cache:
    directories:
    - /home/travis/.gradle/caches/
    - /home/travis/.gradle/wrapper/dists/gradle-1.12-all/
    - /home/travis/.m2/repository/
